src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ApiResource
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $device;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creationDate;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Image", mappedBy="article")
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        if (!$this->creationDate) {
            $this->creationDate = new \DateTime();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(?string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getDevice(): ?string
    {
        return $this->device;
    }

    public function setDevice(?string $device): self
    {
        $this->device = $device;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creationDate;
    }

    public function setCreationDate(\DateTimeInterface $creationDate): self
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getStockMessage(): string
    {
        if ($this->getStock() > 5) {
            $msg = '<span class="text-success">In stock</span>';
        } elseif ($this->getStock() > 0) {
            $msg = '<span class="text-warning"> Only ' . $this->getStock() . ' left</span>';
        } else {
            $msg = '<span class="text-danger">Not available</span>';
        }

        return $msg;
    }

    public function getArticleTitle(): string
    {
        $title = $this->getProduct()->getTitle();

        if ($this->getColor()) {
            $title .= ' - ' . ucfirst($this->getColor());
        }
        if ($this->getSize()) {
            $title .= ' - ' . $this->getSize();
        }
        if ($this->getDevice()) {
            $title .= ' - ' . $this->getDevice();
        }

        return $title;
    }

    public function __toString()
    {
        return $this->getArticleTitle();
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->addArticle($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            $image->removeArticle($this);
        }

        return $this;
    }
}

src/Entity/Cart.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CartRepository")
 * @ApiResource
 */
class Cart
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Orders", inversedBy="carts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $orders;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrders(): ?Orders
    {
        return $this->orders;
    }

    public function setOrders(?Orders $orders): self
    {
        $this->orders = $orders;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Data\Cart\CartData;
use App\Service\Cart\CartService;

use App\Service\Header\TagService;
use App\Repository\ArticleRepository;

use App\Service\Header\HeaderService;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CartController extends AbstractController
{
    protected $header;
    protected $cart;
    protected $serializer;
    private $session;

    public function __construct(HeaderService $header, CartService $cart, SerializerInterface $serializer, SessionInterface $session)
    {
        $this->header = $header;
        $this->cart = $cart;
        $this->serializer = $serializer;
        $this->session = $session;
    }
    /**
     * @Route("/cart/recap", name="cart")
     */
    public function index()
    {
        return $this->render('cart/index.html.twig', [
            'header' => $this->header,
            'cart' => $this->cart->getCart(),
            'index' => 0
        ]);
    }

    /**
     * Add an article into the cart
     * @Route("/product/addToCart", name="cart_add")

     * @param Request $request
     * @return Response
     */
    public function addToCart(Request $request): Response
    {
        $addition = $this->serializer->deserialize($request->getContent(), CartData::class, 'json');
        return $this->json($this->cart->add($addition), 200);
    }

    /**
     * Remove an article from the cart
     * @Route("/product/removeFromCart", name="cart_remove")

     * @param Request $request
     * @return Response
     */
    public function removeFromCart(Request $request): Response
    {
        $removal = $this->serializer->deserialize($request->getContent(), CartData::class, 'json');
        return $this->json($this->cart->remove($removal), 200);
    }

    /**
     * Modify quantity of the selected article
     * @Route("/product/modifyCart", name="cart_modify")

     * @param Request $request
     * @return Response
     */
    public function modifyArticleQuantity(Request $request): Response
    {
        $modification = $this->serializer->deserialize($request->getContent(), CartData::class, 'json');
        return $this->json($this->cart->setQuantity($modification), 200);
    }

    /**
     * Function only for test purpose
     * @Route("/product/showCart", name="cart_show")

     * @param Request $request
     * @param SessionInterface $session
     * @return Response
     */
    public function giveMeCart(Request $request, SessionInterface $session): Response
    {
        $cart = $session->get('cart');

        return $this->json([
            'cart' => $cart
        ], 200);
    }

    /**
     * @Route("/cart/checkout", name="cart_checkout")
     *
     * @param Request $request
     * @return Response
     */
    public function checkout(): Response
    {

        if ($this->getUser()) {
            // dump($this->cart->getCart());
            return $this->render('cart/delivery.html.twig', [
                'header' => $this->header,
                'cart' => $this->cart->getCart(),
                'user' => $this->getUser(),
                'index' => 1
            ]);
        } else {
            $response = new Response(
                'Content',
                Response::HTTP_OK,
                ['content-type' => 'text/html']
            );
            $cookie = new Cookie('logFromCart', 'delivery', \time()+5*60);
            $response->headers->setCookie($cookie);
            $response->send();
            return $this->redirectToRoute('security_login');
        }

        // return $this->json([
        //     'request' => $request->request->all()
        // ], 200);
    }
    /**
     * @Route("/cart/confirm", name="cart_confirm")
     *
     * @param Request $request
     * @return Response
     */
    public function confirmCart(Request $request)
    {
        if ($this->getUser()) {
            $manager = $this->getDoctrine()->getManager();
            $order = $this->cart->getOngoingOrder($this->getUser());
            $articles = $this->cart->getCart()["items"];
            $totalPrice = 0;

            foreach ($articles as $key => $value) {
                $quantity = 0;
                foreach ($value as $newKey => $newValue) {
                    if ($newKey === 'article') {
                        $priceArticle = $newValue->getProduct()->getPrice()->getPriceDf();
                    } elseif ($newKey === 'quantity') {
                        $quantity = $newValue;
                        $totalPrice += $quantity * $priceArticle;
                    }
                }
            }
            $totalPrice += $request->request->get('deliveryChoice');

            $order->setTotalValue($totalPrice);
            $order->setValidationDate(new \DateTime());
            $order->setOrderNumber("CMD" . $order->getValidationDate()->format('Y-m-d-H-i-s') . "-" . $this->getUser()->getId());
            $manager->persist($order);
            $manager->flush();

            $this->session->set('cart', []);

            return $this->redirectToRoute('success');
        } else {
            return $this->redirectToRoute('error');
        }
    }
}

templates/cart/delivery.html.twig
{% extends 'baseCart.html.twig' %}

{% block title %}Delivery
{% endblock %}

{% block body %}

	<div class="col-lg-4 col-md-4 col-sm-5 col-4 mx-auto">
		<div class="col-lg-12 mx-auto border borderSize">
			<h2 class="my-3 text-center">Delivery Options</h1>
			<form action="{{ path('cart_confirm')}}" method="post" id="formD1">
				<div class="text-center">
					<div>
						<input type="radio" id="huey" name="deliveryChoice" value="5.99" required>
						<label for="huey">One Day Delivery</label>
						<label for="huey">5.99€</label>
					</div>
					<div>
						<input type="radio" id="dewey" name="deliveryChoice" value="3.99">
						<label for="dewey">2 Days delivery</label>
						<label for="huey">3.99€</label>
					</div>
					<div>
						<input type="radio" id="louie" name="deliveryChoice" value="0">
						<label for="louie">4 + Days delivery</label>
						<label for="huey">Free</label>
					</div>
				</div>
			</form>
		</div>
	</div>

	<div class="d-flex flex-row justify-content-center mt-5">
		<div class="col-lg-4 col-md-4 col-sm-5">
			<div class="border borderSize ">
				<h2 class="my-3 text-center">Delivery Adress</h1>
				<form action="{{ path('cart_confirm')}}" method="post" id="formD2">
					<div class="text-center">
						<span>Default Adress</span>
					</div>
				</form>
			</div>
		</div>

		<div class="col-lg-4 col-md-4 col-sm-5">
			<div class="border borderSize ">
				<h2 class="my-3 d-inline">Billing Adress</h1>
				<div class="d-inline">
					<input type="checkbox" id="scales" name="scales">
					<label for="scales">Different Adress</label>
				</div>
				<form action="{{ path('cart_confirm')}}" method="post" id="formD3">
					<div class="text-center">
						<div>
							<span>Default Adress</span>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

	<div class="d-flex flex-row justify-content-center mt-5">
		<button type='submit' class="btn btn-primary" onclick="submitForms()">Confirm</button>
	</div>

{% endblock %}
{% block javascripts %}
	<script>
		submitForms = function () {
document.getElementById("formD1").submit();
}
	</script>

{% endblock %}

templates/cart/index.html.twig
{% extends 'baseCart.html.twig' %}

{% block title %}Cart
{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="row justify-content-center align-items-baseline m-2">
			<h1 class="mx-2">Cart</h1>
			<span>(<span id="js_nbr_items">{{ cart.total }}</span>
				products)</span>
		</div>

		<div class="row justify-content-center">
			<div class="col-xl-6 col-sm-5 col-6 justify-content-center" id="js_items_list">
				<form action="{{ path('cart_modify') }}" method="POST" id="quantity_form">
					<!-- start loop articlesInCart -->
					{% for item in cart.items %}
						<div class="item-box row col-10 my-1 p-2 border rounded" id="item_{{ item.article.id }}">
							<img src="{{ item.article.images.0.url }}" width="80px" height="80px">
							<div class="col-10 px-3">
								<div class="row justify-content-between">
									<div class="col-9 article-title">
										<b>{{ item.article.articleTitle }}</b>
									</div>
									<div>
										<span class="article-price">{{ item.article.product.price.priceDF }}</span>
										€</div>
								</div>
								<div class="mt-1 mb-3">{{ item.article.stockMessage | raw }}</div>
								<div class="row justify-content-between">
									<div class="col-8">
										<small class="form-row align-items-baseline">
											<label class="mx-1">Quantity</label>
											<select
												class="js-quantity-selector form-control col-2" data-article-id="{{ item.article.id }}" name="cart[{{ item.article.id }}]">
												<!-- start on loop article stock with twig -->
												{% if item.article.stock < 5 %}
													{% for q in 1..item.article.stock %}
														<option {% if item.quantity == q %} selected {% endif %}>{{ q }}</option>
													{% endfor %}.
												{% else %}
													{% for q in 1..5 %}
														<option {% if item.quantity == q %} selected {% endif %}>{{ q }}</option>
													{% endfor %}
												{% endif %}
												<!-- end on loop article stock with twig -->
											</select>
										</small>
									</div>
									<a href="{{ path('cart_remove') }}" data-article-id="{{ item.article.id }}" class="js-btn-delete">
										<i class="fas fa-trash-alt"></i>
									</a>
								</div>
							</div>
						</div>
					{% else %}
						<div>No registered items in the cart</div>
					{% endfor %}
					<!-- end loop articlesInCart -->
				</form>
			</div>

			<div class="col-xl-3 col-sm-4 col-3">
				<form action="{{ path('cart_checkout') }}" method="POST" id="cart">
					<div class="form-group d-flex border rounded p-2 my-1">
						<label class="col-auto col-form-label">Promo :
						</label>
						<div class="col-6 p-0">
							<input type="text" class="form-control" placeholder="ex: LBB527">
						</div>
					</div>
					<div class="border rounded my-2 px-2">
						<div class="d-flex justify-content-between my-1">
							<div>
								<b>Total excl.taxes :
								</b>
							</div>
							<div>
								<span id="js_totalPriceDF"></span>€</div>
						</div>
						<div class="d-flex justify-content-between my-1">
							<div>
								<b>Discount :
								</b>
							</div>
							<div class="text-success">
								<span id="js_discount">5.00</span>€</div>
						</div>
						<div class="d-flex justify-content-between my-1">
							<div>
								<b>Total incl.taxes :
								</b>
							</div>
							<div>
								<span id="js_totalPriceVAT">59.98</span>€</div>
						</div>
					</div>
					<div class="text-center w-100">
						<button type="submit" id="proceed_btn" form="cart" class="btn btn-warning" {% if cart.items | length == 0 %} disabled {% endif %}>Proceed to checkout</button>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}
{% block javascripts %}
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	{{ encore_entry_script_tags('cart') }}
{% endblock %}